"""empty message

Revision ID: 8c4d27e29e47
Revises: f6e153eba5af
Create Date: 2022-08-15 17:59:08.750975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4d27e29e47'
down_revision = 'f6e153eba5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('employee_no', sa.String(length=20), nullable=False),
    sa.Column('employee_name', sa.String(length=20), nullable=False),
    sa.Column('employee_sex', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
