"""empty message

Revision ID: f6e153eba5af
Revises: 3afd7e1e74a5
Create Date: 2022-08-15 17:58:50.411071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e153eba5af'
down_revision = '3afd7e1e74a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('purchase_no', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_user', sa.String(length=20), nullable=False),
    sa.Column('purchase_phone', sa.String(length=20), nullable=False),
    sa.Column('purchase_email', sa.String(length=20), nullable=False),
    sa.Column('purchase_address', sa.String(length=20), nullable=False),
    sa.Column('purchase_postcode', sa.String(length=20), nullable=False),
    sa.Column('purchase_fax', sa.String(length=20), nullable=False),
    sa.Column('purchase_website', sa.String(length=20), nullable=False),
    sa.Column('purchase_remark', sa.String(length=20), nullable=False),
    sa.Column('purchase_status', sa.String(length=20), nullable=False),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
